name: sisepuede
channels:
  - conda-forge
dependencies:
  - python==3.11
  - geopandas>=1.0.1
  - geopy>=2.1.0
  - juliacall=0.9.25
  - juliapkg=0.1.17
  - matplotlib=3.10.1
  - munch=2.5.0
  - numpy>=2.2.2
  - openpyxl=3.1.2
  - pandas>=2.2.3
  - pyDOE2=1.3.0
  - pyxlsb=1.0.10
  - PyYAML=6.0
  - qpsolvers=4.4.0
  - quadprog=0.1.13
  - rioxarray=0.15.5
  - SQLAlchemy=2.0.37
